// actionTypes.js
export const FETCH_BRANCH_REQUEST = 'FETCH_BRANCH_REQUEST';
export const FETCH_BRANCH_SUCCESS = 'FETCH_BRANCH_SUCCESS';
export const FETCH_BRANCH_FAILURE = 'FETCH_BRANCH_FAILURE';


export const FETCH_BRANCH_DETAILS_REQUEST = 'FETCH_BRANCH_DETAILS_REQUEST';
export const FETCH_BRANCH_DETAILS_SUCCESS = 'FETCH_BRANCH_DETAILS_SUCCESS';
export const FETCH_BRANCH_DETAILS_FAILURE = 'FETCH_BRANCH_DETAILS_FAILURE';

export const UPDATE_BRANCH_DETAILS_REQUEST = 'UPDATE_BRANCH_DETAILS_REQUEST';
export const UPDATE_BRANCH_DETAILS_SUCCESS = 'UPDATE_BRANCH_DETAILS_SUCCESS';
export const UPDATE_BRANCH_DETAILS_FAILURE = 'UPDATE_BRANCH_DETAILS_FAILURE';
export const UPDATE_BRANCH_DETAILS_RESET = 'UPDATE_BRANCH_DETAILS_RESET';

export const ADD_BRANCH_DETAILS_REQUEST = 'ADD_BRANCH_DETAILS_REQUEST';
export const ADD_BRANCH_DETAILS_SUCCESS = 'ADD_BRANCH_DETAILS_SUCCESS';
export const ADD_BRANCH_DETAILS_FAILURE = 'ADD_BRANCH_DETAILS_FAILURE';
export const ADD_BRANCH_DETAILS_RESET = 'ADD_BRANCH_DETAILS_RESET';

export const FETCH_BRANCH_ERROR = 'FETCH_BRANCH_ERROR';