// actionTypes.js
export const FETCH_OFFER_SLIDER_REQUEST = "FETCH_OFFER_SLIDER_REQUEST";
export const FETCH_OFFER_SLIDER_SUCCESS = "FETCH_OFFER_SLIDER_SUCCESS";
export const FETCH_OFFER_SLIDER_FAILURE = "FETCH_OFFER_SLIDER_FAILURE";

export const ADD_OFFER_SLIDER_DETAILS_REQUEST =
  "ADD_OFFER_SLIDER_DETAILS_REQUEST";
export const ADD_OFFER_SLIDER_DETAILS_SUCCESS =
  "ADD_OFFER_SLIDER_DETAILS_SUCCESS";
export const ADD_OFFER_SLIDER_DETAILS_FAILURE =
  "ADD_OFFER_SLIDER_DETAILS_FAILURE";
export const ADD_OFFER_SLIDER_DETAILS_RESET = "ADD_OFFER_SLIDER_DETAILS_RESET";

export const UPDATE_OFFER_SLIDER_DETAILS_REQUEST =
  "UPDATE_OFFER_SLIDER_DETAILS_REQUEST";
export const UPDATE_OFFER_SLIDER_DETAILS_SUCCESS =
  "UPDATE_OFFER_SLIDER_DETAILS_SUCCESS";
export const UPDATE_OFFER_SLIDER_DETAILS_FAILURE =
  "UPDATE_OFFER_SLIDER_DETAILS_FAILURE";
export const UPDATE_OFFER_SLIDER_DETAILS_RESET =
  "UPDATE_OFFER_SLIDER_DETAILS_RESET";
//________________________________________________________________________________________

export const FETCH_OFFERS_DETAILS_REQUEST = "FETCH_OFFERS_DETAILS_REQUEST";
export const FETCH_OFFERS_DETAILS_SUCCESS = "FETCH_OFFERS_DETAILS_SUCCESS";
export const FETCH_OFFERS_DETAILS_FAILURE = "FETCH_OFFERS_DETAILS_FAILURE";

export const FETCH_OFFERS_REQUEST = "FETCH_OFFERS_REQUEST";
export const FETCH_OFFERS_SUCCESS = "FETCH_OFFERS_SUCCESS";
export const FETCH_OFFERS_FAILURE = "FETCH_OFFERS_FAILURE";

export const ADD_OFFER_DETAILS_REQUEST = "ADD_OFFER_DETAILS_REQUEST";
export const ADD_OFFER_DETAILS_SUCCESS = "ADD_OFFER_DETAILS_SUCCESS";
export const ADD_OFFER_DETAILS_FAILURE = "ADD_OFFER_DETAILS_FAILURE";
export const ADD_OFFER_DETAILS_RESET = "ADD_OFFER_DETAILS_RESET";

export const UPDATE_OFFER_DETAILS_REQUEST = "UPDATE_OFFER_DETAILS_REQUEST";
export const UPDATE_OFFER_DETAILS_SUCCESS = "UPDATE_OFFER_DETAILS_SUCCESS";
export const UPDATE_OFFER_DETAILS_FAILURE = "UPDATE_OFFER_DETAILS_FAILURE";
export const UPDATE_OFFER_DETAILS_RESET = "UPDATE_OFFER_DETAILS_RESET";

export const FETCH_OFFER_ERROR = "FETCH_OFFER_ERROR";
