// actionTypes.js
export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';
export const FETCH_SEARCH_RESET = 'FETCH_SEARCH_RESET';
export const FETCH_SEARCH_ERROR = 'FETCH_SEARCH_ERROR';