// actionTypes.js
export const FETCH_WEBSITE_REQUEST = 'FETCH_WEBSITE_REQUEST';
export const FETCH_WEBSITE_SUCCESS = 'FETCH_WEBSITE_SUCCESS';
export const FETCH_WEBSITE_FAILURE = 'FETCH_WEBSITE_FAILURE';


export const FETCH_WEBSITE_DETAILS_REQUEST = 'FETCH_WEBSITE_DETAILS_REQUEST';
export const FETCH_WEBSITE_DETAILS_SUCCESS = 'FETCH_WEBSITE_DETAILS_SUCCESS';
export const FETCH_WEBSITE_DETAILS_FAILURE = 'FETCH_WEBSITE_DETAILS_FAILURE';

export const UPDATE_WEBSITE_DETAILS_REQUEST = 'UPDATE_WEBSITE_DETAILS_REQUEST';
export const UPDATE_WEBSITE_DETAILS_SUCCESS = 'UPDATE_WEBSITE_DETAILS_SUCCESS';
export const UPDATE_WEBSITE_DETAILS_FAILURE = 'UPDATE_WEBSITE_DETAILS_FAILURE';
export const UPDATE_WEBSITE_DETAILS_RESET = 'UPDATE_WEBSITE_DETAILS_RESET';

export const ADD_WEBSITE_DETAILS_REQUEST = 'ADD_WEBSITE_DETAILS_REQUEST';
export const ADD_WEBSITE_DETAILS_SUCCESS = 'ADD_WEBSITE_DETAILS_SUCCESS';
export const ADD_WEBSITE_DETAILS_FAILURE = 'ADD_WEBSITE_DETAILS_FAILURE';
export const ADD_WEBSITE_DETAILS_RESET = 'ADD_WEBSITE_DETAILS_RESET';

export const FETCH_WEBSITE_ERROR = 'FETCH_WEBSITE_ERROR';